import fs from "node:fs";
import path from "node:path";
import { z } from "zod";
import { McpServer, ResourceTemplate } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { CallToolResult } from "@modelcontextprotocol/sdk/types.js";
import type { ResolvedConfig } from "./config.js";
import type { VaultIndex, NoteRow } from "./vault/index.js";
import { section, stripConnections, stripTitleHeading, firstParagraph } from "./vault/parse.js";
import { Policy, type Principal, ALL_SCOPES } from "./policy.js";
import { Audit } from "./audit.js";
import { buildIdentity } from "./identity.js";
import { buildContext, buildContextHybrid } from "./context.js";
import { judge, parseMemoryBlocks } from "./memory.js";

export interface Deps {
  cfg: ResolvedConfig;
  index: VaultIndex;
  policy: Policy;
  audit: Audit;
  /** Principal used when the transport carries no auth info (stdio). */
  defaultPrincipal: Principal;
}

interface Extra {
  authInfo?: { clientId: string; scopes: string[] };
  sessionId?: string;
}

function principalOf(extra: Extra, d: Deps): Principal {
  if (extra.authInfo) {
    return { clientId: extra.authInfo.clientId, scopes: new Set(extra.authInfo.scopes), transport: "http", sessionId: extra.sessionId };
  }
  return { ...d.defaultPrincipal, sessionId: extra.sessionId };
}

const text = (s: string): CallToolResult => ({ content: [{ type: "text", text: s }] });
const fail = (s: string): CallToolResult => ({ content: [{ type: "text", text: s }], isError: true });

const today = () => new Date().toISOString().slice(0, 10);
const daysAgo = (n: number) => new Date(Date.now() - n * 86400_000).toISOString().slice(0, 10);

function meta(n: NoteRow, index: VaultIndex): string {
  const topics = index.topicsOf(n.id);
  const bits = [`type: ${n.type}`, n.project ? `project: ${n.project}` : null, `modified: ${n.modified}`, topics.length ? `topics: ${topics.join(", ")}` : null];
  return bits.filter(Boolean).join(" · ");
}

function line(n: NoteRow, index: VaultIndex, extra = ""): string {
  return `- **${n.title}** \`${n.id}\` — ${meta(n, index)}${extra ? ` — ${extra}` : ""}`;
}

function safeFileName(title: string): string {
  return title.replace(/[\\/:*?"<>|\x00-\x1f]/g, "-").replace(/\s+/g, " ").trim().slice(0, 120) || "untitled";
}

function yq(s: string): string {
  return JSON.stringify(s);
}

/** Replace the text under one heading, up to the next heading of the same or higher level. Fence-aware,
 *  so `# comment` lines inside code blocks are not taken for headings. Expects "\n" line endings. */
function replaceSection(src: string, heading: string, content: string): string {
  const lines = src.split("\n");
  let start = 0;
  if (lines[0] === "---") {
    const end = lines.indexOf("---", 1);
    if (end > 0) start = end + 1;
  }
  const want = heading.replace(/^#+\s*/, "").trim().toLowerCase();
  const heads: { i: number; level: number; text: string }[] = [];
  let fence: string | null = null;
  for (let i = start; i < lines.length; i++) {
    const f = /^\s*(```|~~~)/.exec(lines[i]);
    if (f) {
      fence = fence ? (f[1] === fence ? null : fence) : f[1];
      continue;
    }
    if (fence) continue;
    const h = /^(#{1,6})\s+(.*?)\s*#*\s*$/.exec(lines[i]);
    if (h) heads.push({ i, level: h[1].length, text: h[2].trim().toLowerCase() });
  }
  const matches = heads.filter((h) => h.text === want);
  if (matches.length !== 1)
    throw new Error(matches.length ? `${matches.length} sections are headed "${heading}"; use old_text instead.` : `No section headed "${heading}".`);
  const m = matches[0];
  const next = heads.find((h) => h.i > m.i && h.level <= m.level);
  const body = content.trim();
  return [...lines.slice(0, m.i), lines[m.i], "", ...(body ? [body, ""] : []), ...lines.slice(next ? next.i : lines.length)].join("\n");
}

export function instructions(cfg: ResolvedConfig): string {
  return (
    `This server is ${cfg.owner}'s second brain: a live Obsidian vault of their projects, decisions, runbooks, preferences and memory.\n\n` +
    `FIRST ACTION in every conversation: call brain_identity with no arguments, before answering anything, and adopt what it returns ` +
    `as standing context (who the owner is, how they want you to work, what they are working on). Do not ask the owner to re-explain themselves.\n\n` +
    `Then: brain_context for any question the vault might answer (one call, returns the relevant sections), brain_search to locate notes, ` +
    `brain_project before discussing a project, brain_graph to move between related notes, brain_read for full text, ` +
    `brain_recent for "what am I working on". Record durable facts with brain_remember and durable documents with brain_capture.\n\n` +
    `Hand-written notes and hubs live in Notes/ and Captures/: create or replace them with brain_write, change part of one with brain_edit, ` +
    `and reorganise with brain_move / brain_delete (deletes go to .trash/). Everything else is regenerated by the vault pipeline and is read-only.\n\n` +
    `When brain_context or brain_search reports coverage "none", say that the vault does not record it instead of answering from general knowledge; ` +
    `on "thin", answer with that caveat.\n\n` +
    `All content is confidential to the owner. Never reproduce credentials; keep [REDACTED:*] markers as-is.`
  );
}

export function createBrainServer(d: Deps): McpServer {
  const { cfg, index, policy, audit } = d;
  const server = new McpServer({ name: "second-brain", version: "0.1.0" }, { instructions: instructions(cfg) });

  const readable = (rows: NoteRow[], p: Principal) => rows.filter((n) => policy.canRead(n, p));

  // ------------------------------------------------------------ identity
  server.registerTool(
    "brain_identity",
    {
      title: "Load the owner's identity and standing context",
      description:
        "Call this FIRST in every conversation. Returns who the owner is, their preferences and feedback rules, the projects they run, and what they touched recently. Adopt it as your persona and working context. Pass `topic` (a few words about what the conversation is about) to get a smaller bundle with only the memory notes that apply.",
      inputSchema: {
        topic: z.string().max(200).optional().describe("What this conversation is about, e.g. 'interview prep' or 'database backups'. Omit for the full bundle."),
      },
      annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
    },
    async (args, extra) => {
      const p = principalOf(extra as Extra, d);
      return audit.run("brain_identity", p, args, () => {
        const { text: t, notes } = buildIdentity(cfg, index, policy, p, args.topic);
        const r = policy.redact(t);
        return { result: text(r.text), notes, redactions: r.count };
      });
    },
  );

  // ------------------------------------------------------------ context
  server.registerTool(
    "brain_context",
    {
      title: "Get the vault sections that answer a question",
      description:
        "One call that returns the most relevant sections from across the vault for a question, with source note ids. Use this before brain_search when you need to answer or reason about something the owner may have written down. Ask in plain words: retrieval is hybrid (keywords + meaning + a reranker), so paraphrases work; still include specific nouns, ids and dates when you have them. The reply states its coverage (good / thin / none).",
      inputSchema: {
        question: z.string().min(3).max(500).describe("The question or topic, in plain words with specific nouns"),
        project: z.string().optional().describe("Restrict to one project"),
        budget_chars: z.number().int().min(2000).max(60000).optional().describe("Size cap for the returned pack (default from config, ~18000)"),
      },
      annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
    },
    async (args, extra) => {
      const p = principalOf(extra as Extra, d);
      return audit.run("brain_context", p, args, async () => {
        const r = await buildContextHybrid(cfg, index, policy, p, args.question, { project: args.project, budgetChars: args.budget_chars });
        return { result: text(r.text), notes: r.notes };
      });
    },
  );

  // ------------------------------------------------------------ search
  server.registerTool(
    "brain_search",
    {
      title: "Search the vault",
      description:
        "Full-text search across every note with optional filters. Returns ranked hits with snippets and note ids for brain_read. Keywords or a short question both work (hybrid keyword + semantic search with spelling correction); the reply states its coverage.",
      inputSchema: {
        query: z.string().min(1).describe("Keywords to search for"),
        project: z.string().optional().describe("Restrict to one project, e.g. 'Website Redesign'"),
        type: z.enum(["note", "runbook", "agent", "progress", "research", "architecture", "plan", "decision", "audit", "spec", "hub", "concept"]).optional(),
        topic: z.string().optional().describe("Restrict to notes tagged with a concept, e.g. 'OAuth'"),
        since: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Only notes modified on/after this date"),
        limit: z.number().int().min(1).max(50).optional().default(10),
      },
      annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
    },
    async (args, extra) => {
      const p = principalOf(extra as Extra, d);
      return audit.run("brain_search", p, args, async () => {
        const { hits, coverage, corrections } = await index.searchHybrid(args.query, { project: args.project, type: args.type, topic: args.topic, since: args.since, limit: args.limit * 2 });
        const visible = hits.filter((h) => policy.canRead({ id: h.id, project: h.project, visibility: index.get(h.id)?.visibility ?? null }, p)).slice(0, args.limit);
        const spelling = corrections.length ? ` (spelling read as ${corrections.join(", ")})` : "";
        if (!visible.length) {
          const why = coverage === "none" ? "The vault does not record this; say so rather than guessing." : "Try fewer or different keywords, or drop the filters.";
          return { result: text(`No notes matched "${args.query}"${spelling}. Coverage: ${coverage}. ${why}`), notes: [] };
        }
        const caveat = coverage === "thin" ? " The best match is weak; treat it as partial evidence." : "";
        const lines = visible.map((h) => `- **${h.title}** \`${h.id}\` — ${h.type}${h.project ? ` · ${h.project}` : ""} · ${h.modified}\n  ${policy.redact(h.snippet.replace(/\s+/g, " ")).text}`);
        return { result: text(`${visible.length} hit(s) for "${args.query}"${spelling}. Coverage: ${coverage}.${caveat}\n\n${lines.join("\n")}`), notes: visible.map((h) => h.id) };
      });
    },
  );

  // ------------------------------------------------------------ read
  server.registerTool(
    "brain_read",
    {
      title: "Read a note",
      description: "Return one note in full (or one section of it) by note id, title, or wikilink target. Includes frontmatter metadata, topics, and links.",
      inputSchema: {
        note: z.string().min(1).describe("Note id (vault path), exact title, or [[wikilink]]"),
        section: z.string().optional().describe("Heading text to return only that section"),
        include_connections: z.boolean().optional().default(false).describe("Keep the generated '## Connections' trailer"),
      },
      annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
    },
    async (args, extra) => {
      const p = principalOf(extra as Extra, d);
      return audit.run("brain_read", p, args, () => {
        const n = index.resolve(args.note);
        if (!n || !policy.canRead(n, p)) return { result: fail(`No readable note matches "${args.note}". Use brain_search to find the id.`), notes: [] };
        let body = stripTitleHeading(args.include_connections ? n.body : stripConnections(n.body), n.title);
        if (args.section) {
          const s = section(body, args.section);
          if (!s) return { result: fail(`Note "${n.title}" has no section titled "${args.section}".`), notes: [n.id] };
          body = s;
        }
        const r = policy.redact(body.trim());
        const out = n.project ? [n.project] : [];
        const related = index.outgoing(n.id).filter((l) => l.note && l.note.id !== n.id).map((l) => l.note!.title).filter((t) => !out.includes(t));
        const header = `# ${n.title}\n\`${n.id}\` · ${meta(n, index)}${related.length ? `\nlinks: ${[...new Set(related)].slice(0, 25).join(", ")}` : ""}\n\n`;
        return { result: text(header + r.text), notes: [n.id], redactions: r.count };
      });
    },
  );

  // ------------------------------------------------------------ project
  server.registerTool(
    "brain_project",
    {
      title: "Project briefing",
      description:
        "One-call briefing on a project: what it is, its notes grouped by type, latest progress entries, decisions, and what changed recently. Call this before discussing any project. Omit the project name to list all projects.",
      inputSchema: {
        project: z.string().optional().describe("Project / hub name, e.g. 'Website Redesign'. Omit to list projects."),
        recent_days: z.number().int().min(1).max(365).optional().default(30),
      },
      annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
    },
    async (args, extra) => {
      const p = principalOf(extra as Extra, d);
      return audit.run("brain_project", p, args, () => {
        if (!args.project) {
          const hubs = readable(index.hubs(), p);
          const lines = hubs.map((h) => `- **${h.title}** — ${firstParagraph(h.body).slice(0, 200)}`);
          return { result: text(`Projects (${hubs.length}):\n\n${lines.join("\n")}`), notes: hubs.map((h) => h.id) };
        }
        const hub = index.hubs().find((h) => h.title.toLowerCase() === args.project!.toLowerCase()) ?? index.resolve(args.project);
        const name = hub?.type === "hub" ? hub.title : args.project;
        const notes = readable(index.list({ project: name, limit: 500 }), p);
        if (!notes.length && !(hub && policy.canRead(hub, p))) return { result: fail(`No project named "${args.project}". Call brain_project with no arguments to list projects.`), notes: [] };
        const byType = new Map<string, NoteRow[]>();
        for (const n of notes) byType.set(n.type, [...(byType.get(n.type) ?? []), n]);
        const sections: string[] = [];
        sections.push(`# ${name}\n`);
        if (hub && policy.canRead(hub, p)) sections.push(`${firstParagraph(hub.body)}\n`);
        const progress = (byType.get("progress") ?? []).slice(0, 5);
        if (progress.length) {
          sections.push(`## Latest progress\n\n${progress.map((n) => `### ${n.title} · ${n.modified}\n${policy.redact(stripTitleHeading(stripConnections(n.body), n.title)).text.trim().slice(0, 900)}`).join("\n\n")}\n`);
        }
        const decisions = byType.get("decision") ?? [];
        if (decisions.length) sections.push(`## Decisions\n\n${decisions.map((n) => line(n, index, firstParagraph(n.body).slice(0, 160))).join("\n")}\n`);
        const since = daysAgo(args.recent_days);
        const changed = notes.filter((n) => n.modified >= since).slice(0, 15);
        if (changed.length) sections.push(`## Changed in the last ${args.recent_days} days\n\n${changed.map((n) => line(n, index)).join("\n")}\n`);
        const order = ["architecture", "spec", "plan", "runbook", "agent", "research", "audit", "note"];
        for (const t of [...order, ...[...byType.keys()].filter((k) => !order.includes(k) && k !== "progress" && k !== "decision")]) {
          const rows = byType.get(t);
          if (!rows?.length) continue;
          sections.push(`## ${t} (${rows.length})\n\n${rows.slice(0, 40).map((n) => `- **${n.title}** \`${n.id}\` · ${n.modified}`).join("\n")}${rows.length > 40 ? `\n- … ${rows.length - 40} more` : ""}\n`);
        }
        return { result: text(sections.join("\n")), notes: [hub?.id, ...notes.map((n) => n.id)].filter((x): x is string => !!x) };
      });
    },
  );

  // ------------------------------------------------------------ graph
  server.registerTool(
    "brain_graph",
    {
      title: "Explore the link graph",
      description:
        "Neighbours of a note, hub, or concept: outgoing links, backlinks, and notes sharing the same topics. For a concept (e.g. 'OAuth') this shows every project that touches it. Use it to hop sideways between projects.",
      inputSchema: {
        note: z.string().min(1).describe("Note id, title, concept name, or [[wikilink]]"),
        limit: z.number().int().min(1).max(100).optional().default(25),
      },
      annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
    },
    async (args, extra) => {
      const p = principalOf(extra as Extra, d);
      return audit.run("brain_graph", p, args, () => {
        const n = index.resolve(args.note);
        if (!n || !policy.canRead(n, p)) return { result: fail(`No readable note matches "${args.note}".`), notes: [] };
        const out = index.outgoing(n.id).filter((l) => l.note && l.note.id !== n.id && policy.canRead(l.note, p));
        const back = readable(index.backlinks(n.id, args.limit), p);
        const shared = index.sharedTopicNeighbours(n.id, args.limit).filter((s) => policy.canRead(s.note, p));
        const parts = [`# ${n.title}\n\`${n.id}\` · ${meta(n, index)}\n`];
        if (out.length) parts.push(`## Links out (${out.length})\n\n${out.slice(0, args.limit).map((l) => line(l.note!, index)).join("\n")}\n`);
        if (back.length) {
          const byProject = new Map<string, NoteRow[]>();
          for (const b of back) byProject.set(b.project ?? "(no project)", [...(byProject.get(b.project ?? "(no project)") ?? []), b]);
          const blocks = [...byProject.entries()].map(([proj, rows]) => `**${proj}**\n${rows.map((r) => line(r, index)).join("\n")}`);
          parts.push(`## Backlinks (${back.length})\n\n${blocks.join("\n\n")}\n`);
        }
        if (shared.length) parts.push(`## Shares topics with\n\n${shared.map((s) => line(s.note, index, `shares ${s.shared.join(", ")}`)).join("\n")}\n`);
        if (parts.length === 1) parts.push("No links in either direction.");
        return { result: text(parts.join("\n")), notes: [n.id, ...out.map((l) => l.note!.id), ...back.map((b) => b.id)] };
      });
    },
  );

  // ------------------------------------------------------------ recent
  server.registerTool(
    "brain_recent",
    {
      title: "What changed recently",
      description: "Notes modified in the last N days, newest first. Answers 'what am I working on' and 'what did I do last week'. Hubs and concepts are excluded unless include_structural is set.",
      inputSchema: {
        days: z.number().int().min(1).max(365).optional().default(14),
        project: z.string().optional(),
        limit: z.number().int().min(1).max(200).optional().default(30),
        include_structural: z.boolean().optional().default(false),
      },
      annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
    },
    async (args, extra) => {
      const p = principalOf(extra as Extra, d);
      return audit.run("brain_recent", p, args, () => {
        const rows = readable(index.recent(daysAgo(args.days), { limit: args.limit, project: args.project, includeStructural: args.include_structural }), p);
        if (!rows.length) return { result: text(`Nothing modified in the last ${args.days} days${args.project ? ` in ${args.project}` : ""}.`), notes: [] };
        const lines = rows.map((n) => line(n, index, policy.redact(firstParagraph(stripConnections(n.body))).text.slice(0, 160)));
        return { result: text(`${rows.length} note(s) modified since ${daysAgo(args.days)}:\n\n${lines.join("\n")}`), notes: rows.map((n) => n.id) };
      });
    },
  );

  // ------------------------------------------------------------ capture (write)
  const captureDirAbs = path.join(cfg.vaultDir, cfg.captureDir);
  const writeCaptured = (rel: string, content: string) => {
    const abs = path.resolve(cfg.vaultDir, rel);
    if (!abs.startsWith(captureDirAbs + path.sep) && abs !== captureDirAbs) throw new Error("write outside capture folder refused");
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, content, "utf8");
    index.upsertFile(abs);
    return abs;
  };

  server.registerTool(
    "brain_capture",
    {
      title: "Save a durable note",
      description:
        "Write a new note into the vault's capture folder with graph-ready frontmatter. Use for plans, decisions, ideas, meeting notes, or session logs the owner wants to keep. Not for one-line facts (use brain_remember).",
      inputSchema: {
        title: z.string().min(3).max(140).describe("Specific noun phrase, not a filename"),
        body: z.string().min(1).describe("Markdown body. Link concepts inline with [[Concept]] on first mention."),
        kind: z.enum(["note", "idea", "decision", "plan", "log", "research"]).optional().default("note"),
        project: z.string().optional().describe("Project hub name this belongs to, e.g. 'Website Redesign'"),
        topics: z.array(z.string()).max(8).optional().describe("Concept names, e.g. ['OAuth', 'RAG']"),
      },
      annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
    },
    async (args, extra) => {
      const p = principalOf(extra as Extra, d);
      return audit.run("brain_capture", p, args, () => {
        if (!policy.canWrite(p)) return { result: fail("This connection has no write scope."), notes: [] };
        const date = today();
        let rel = `${cfg.captureDir}/${date} ${safeFileName(args.title)}.md`;
        for (let i = 2; fs.existsSync(path.join(cfg.vaultDir, rel)); i++) rel = `${cfg.captureDir}/${date} ${safeFileName(args.title)} (${i}).md`;
        const projectHub = args.project ? index.hubs().find((h) => h.title.toLowerCase() === args.project!.toLowerCase()) : undefined;
        const warn = args.project && !projectHub ? `\n\nNote: no hub named "${args.project}" exists; the project link will stay unresolved until one is created.` : "";
        const fmLines = [
          "---",
          `title: ${yq(args.title)}`,
          `type: ${args.kind}`,
          ...(args.project ? [`project: ${yq(`[[${projectHub?.title ?? args.project}]]`)}`] : []),
          ...(args.topics?.length ? ["topics:", ...args.topics.map((t) => `  - ${yq(`[[${t}]]`)}`)] : []),
          "tags:",
          "  - captured",
          `  - type/${args.kind}`,
          ...(projectHub ? [`  - project/${projectHub.title.toLowerCase().replace(/\s+/g, "-")}`] : []),
          `source: ${yq(`mcp:${p.clientId}`)}`,
          `captured: ${date}`,
          `modified: ${date}`,
          "---",
          "",
        ];
        const content = fmLines.join("\n") + `# ${args.title}\n\n${args.body.trim()}\n`;
        writeCaptured(rel, content);
        return { result: text(`Saved \`${rel}\`.${warn}`), notes: [rel] };
      });
    },
  );

  server.registerTool(
    "brain_remember",
    {
      title: "Remember a durable fact",
      description:
        "Append one durable fact about the owner to their memory file: a preference, a correction on how to work, a project constraint, or a reference. It becomes part of brain_identity immediately. Include why it matters and how to apply it. Near-duplicates of existing memory are refused; pass force=true to store anyway. Do not store session trivia.",
      inputSchema: {
        fact: z.string().min(5).max(2000),
        category: z.enum(["user", "feedback", "project", "reference"]).describe("user = who they are; feedback = how to work with them; project = ongoing work; reference = pointer"),
        why: z.string().max(1000).optional(),
        how_to_apply: z.string().max(1000).optional(),
        force: z.boolean().optional().default(false).describe("Store even if it looks like a duplicate"),
      },
      annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
    },
    async (args, extra) => {
      const p = principalOf(extra as Extra, d);
      return audit.run("brain_remember", p, args, () => {
        if (!policy.canWrite(p)) return { result: fail("This connection has no write scope."), notes: [] };
        const abs = path.join(cfg.vaultDir, cfg.memoryFile);
        const stamp = new Date().toISOString().slice(0, 16).replace("T", " ");
        let existing = "";
        if (fs.existsSync(abs)) existing = fs.readFileSync(abs, "utf8");
        else
          existing =
            ["---", 'title: "Memory"', "type: note", `project: ${yq(`[[${cfg.identity.memoryProject}]]`)}`, "tags:", "  - captured", "  - memory", `captured: ${today()}`, `modified: ${today()}`, "---", "", "# Memory", "", "Facts recorded through the second-brain MCP. Newest at the bottom.", ""].join("\n");
        const blocks = parseMemoryBlocks(existing);
        const verdict = judge(args.fact, blocks);
        if (verdict.kind === "duplicate" && !args.force) {
          const m = verdict.match!;
          return {
            result: fail(`Not stored: this looks like a duplicate of the ${m.category} fact recorded ${m.id}:\n\n> ${m.text.split("\n")[0]}\n\nIf it is genuinely new, call again with force=true.`),
            notes: [cfg.memoryFile],
          };
        }
        // Related generated memory notes, for the caller's awareness only.
        const related = index
          .search(args.fact, { project: cfg.identity.memoryProject, limit: 3 })
          .filter((h) => h.id !== cfg.memoryFile)
          .map((h) => h.title);
        existing = existing.replace(/^modified: .*$/m, `modified: ${today()}`);
        const supersedes = verdict.kind === "update" ? ["", `**Supersedes:** ${verdict.match!.id} · ${verdict.match!.category}`] : [];
        const block = [`## ${stamp} · ${args.category}`, "", args.fact.trim(), ...(args.why ? ["", `**Why:** ${args.why.trim()}`] : []), ...(args.how_to_apply ? ["", `**How to apply:** ${args.how_to_apply.trim()}`] : []), ...supersedes, "", `*via mcp:${p.clientId}*`, ""].join("\n");
        writeCaptured(cfg.memoryFile, existing.trimEnd() + "\n\n" + block);
        const notes: string[] = [];
        if (verdict.kind === "update") notes.push(`Marked as superseding the ${verdict.match!.category} fact from ${verdict.match!.id}.`);
        if (related.length) notes.push(`Related memory notes already exist: ${related.join("; ")}.`);
        if (blocks.length + 1 >= 200) notes.push(`Memory file now holds ${blocks.length + 1} facts; consider pruning.`);
        return { result: text(`Remembered (${args.category}). It is now part of brain_identity.${notes.length ? "\n" + notes.join("\n") : ""}`), notes: [cfg.memoryFile] };
      });
    },
  );

  // ------------------------------------------------------------ hand-written notes (write / edit / move / delete)
  // Only folders the vault pipeline keeps (emit.py's KEEP list) are writable: everything else is regenerated and
  // would silently lose the change. The memory file stays append-only through brain_remember.
  const writableDirs = (cfg.writableDirs ?? [cfg.captureDir, "Notes"]).map((dir) => dir.replace(/\\/g, "/").replace(/^\/+|\/+$/g, ""));
  const writable = (ref: string): { abs: string; rel: string } => {
    const abs = path.resolve(cfg.vaultDir, ref.replace(/\\/g, "/").replace(/^\/+/, ""));
    const rel = path.relative(cfg.vaultDir, abs).split(path.sep).join("/");
    if (!rel || rel === ".." || rel.startsWith("../") || path.isAbsolute(rel)) throw new Error("That path is outside the vault.");
    if (!rel.toLowerCase().endsWith(".md")) throw new Error("Only Markdown notes (.md) can be written.");
    if (rel.split("/").some((seg) => seg.startsWith("."))) throw new Error("Hidden folders are not writable.");
    if (!writableDirs.some((dir) => rel.startsWith(dir + "/")))
      throw new Error(`Only notes under ${writableDirs.map((dir) => `${dir}/`).join(" or ")} can be changed; everything else is regenerated by the vault pipeline.`);
    if (rel.toLowerCase() === cfg.memoryFile.replace(/\\/g, "/").toLowerCase()) throw new Error(`${cfg.memoryFile} is append-only; use brain_remember.`);
    return { abs, rel };
  };
  /** A note the caller names by id, title or [[wikilink|alias]], checked for write access. */
  const writableNote = (ref: string, p: Principal): { note: NoteRow; abs: string; rel: string } => {
    const note = index.resolve(ref.replace(/\|[^\]]*/, ""));
    if (!note || !policy.canRead(note, p)) throw new Error(`Note not found: ${ref}`);
    return { note, ...writable(note.id) };
  };
  /** Record the links that resolve to a note now; the returned check, run after the note moved or went,
   *  reports only those that no longer resolve (a same-titled note or a kept title can still catch them). */
  const linksInto = (id: string) => {
    const refs = index.backlinks(id, 50).flatMap((n) => index.outgoing(n.id).filter((o) => o.note?.id === id).map((o) => ({ from: n.id, target: o.target })));
    return () => {
      const broken = [...new Set(refs.filter((r) => !index.resolve(r.target)).map((r) => r.from))];
      return broken.length ? `\n\n${broken.length} note(s) now have links that resolve to nothing: ${broken.slice(0, 5).map((b) => `\`${b}\``).join(", ")}.` : "";
    };
  };
  const guardedWrite = (tool: string, p: Principal, args: unknown, fn: () => { result: CallToolResult; notes: string[] }) =>
    audit.run(tool, p, args, () => {
      if (!policy.canWrite(p)) return { result: fail("This connection has no write scope."), notes: [] };
      try {
        return fn();
      } catch (e) {
        return { result: fail((e as Error).message), notes: [] };
      }
    });

  server.registerTool(
    "brain_write",
    {
      title: "Create or replace a hand-written note",
      description:
        "Create a note at a path you choose under Notes/ or Captures/, or replace one there with overwrite=true. Use it for hubs, guides and runbooks maintained by hand. Unlike brain_capture you set the type, including 'hub': a hub groups every note whose frontmatter project matches its title. Generated notes elsewhere in the vault cannot be written.",
      inputSchema: {
        path: z.string().min(4).max(240).describe("Vault path, e.g. 'Notes/Harbor Ledger.md'"),
        title: z.string().min(1).max(140),
        body: z.string().min(1).describe("Markdown body, without frontmatter or the # title heading"),
        type: z.string().regex(/^[a-z][a-z-]{1,23}$/).optional().default("note").describe("note, hub, moc, guide, runbook, plan, decision, ..."),
        project: z.string().optional().describe("Hub this note belongs to, e.g. 'Harbor Ledger'"),
        topics: z.array(z.string()).max(8).optional().describe("Concept names, e.g. ['OAuth', 'RAG']"),
        summary: z.string().max(300).optional().describe("One line; Start Here shows it next to Notes/ guides"),
        order: z.number().int().min(0).max(999).optional().describe("Position among Notes/ guides on Start Here"),
        overwrite: z.boolean().optional().default(false).describe("Replace the note if the path already exists"),
      },
      annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
    },
    async (args, extra) => {
      const p = principalOf(extra as Extra, d);
      return guardedWrite("brain_write", p, args, () => {
        const { abs, rel } = writable(args.path);
        const exists = fs.existsSync(abs);
        if (exists && !args.overwrite) return { result: fail(`\`${rel}\` already exists. Pass overwrite=true to replace it, or use brain_edit.`), notes: [rel] };
        const captured = (exists && /^captured: (.*)$/m.exec(fs.readFileSync(abs, "utf8"))?.[1]?.trim()) || today();
        const projectHub = args.project ? index.hubs().find((h) => h.title.toLowerCase() === args.project!.toLowerCase()) : undefined;
        const fm = [
          "---",
          `title: ${yq(args.title)}`,
          `type: ${args.type}`,
          ...(args.summary ? [`summary: ${yq(args.summary)}`] : []),
          ...(args.order !== undefined ? [`order: ${args.order}`] : []),
          ...(args.project ? [`project: ${yq(`[[${projectHub?.title ?? args.project}]]`)}`] : []),
          ...(args.topics?.length ? ["topics:", ...args.topics.map((t) => `  - ${yq(`[[${t}]]`)}`)] : []),
          "tags:",
          "  - hand-written",
          `  - type/${args.type}`,
          `source: ${yq(`mcp:${p.clientId}`)}`,
          `captured: ${captured}`,
          `modified: ${today()}`,
          "---",
          "",
        ];
        fs.mkdirSync(path.dirname(abs), { recursive: true });
        fs.writeFileSync(abs, fm.join("\n") + `# ${args.title}\n\n${args.body.trim()}\n`, "utf8");
        index.upsertFile(abs);
        const notes: string[] = [];
        if (args.type === "hub") {
          notes.push(`Hub "${args.title}" now groups every note whose frontmatter project is [[${args.title}]].`);
          const twin = index.hubs().find((h) => h.title.toLowerCase() === args.title.toLowerCase() && h.id !== rel);
          if (twin) notes.push(`Another hub with this title exists at \`${twin.id}\`; remove one of them.`);
        }
        if (args.project && !projectHub) notes.push(`No hub named "${args.project}" exists yet; the project link stays unresolved until one does.`);
        return { result: text(`${exists ? "Replaced" : "Created"} \`${rel}\`.${notes.length ? "\n\n" + notes.join("\n") : ""}`), notes: [rel] };
      });
    },
  );

  server.registerTool(
    "brain_edit",
    {
      title: "Edit part of a hand-written note",
      description:
        "Change part of a note under Notes/ or Captures/ without rewriting it. Give exactly one of: old_text + new_text (old_text must occur exactly once; new_text may be empty), section + content (replaces everything under that heading up to the next heading of the same or higher level; the heading itself stays), or append. Generated notes and the memory file cannot be edited.",
      inputSchema: {
        note: z.string().min(1).describe("Note id (vault path), title or [[wikilink]]"),
        old_text: z.string().min(1).optional().describe("Exact text to replace; must occur exactly once"),
        new_text: z.string().optional(),
        section: z.string().min(1).optional().describe("Heading text of the section to replace, without the # marks"),
        content: z.string().optional().describe("New text for that section"),
        append: z.string().min(1).optional().describe("Markdown to add at the end of the note"),
      },
      annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: false },
    },
    async (args, extra) => {
      const p = principalOf(extra as Extra, d);
      return guardedWrite("brain_edit", p, args, () => {
        const modes = [args.old_text !== undefined, args.section !== undefined, args.append !== undefined].filter(Boolean).length;
        if (modes !== 1) return { result: fail("Give exactly one of: old_text + new_text, section + content, or append."), notes: [] };
        const { abs, rel } = writableNote(args.note, p);
        const raw = fs.readFileSync(abs, "utf8");
        const eol = raw.includes("\r\n") ? "\r\n" : "\n";
        const src = raw.replace(/\r\n/g, "\n");
        const lf = (s: string) => s.replace(/\r\n/g, "\n");
        let out: string;
        if (args.old_text !== undefined) {
          if (args.new_text === undefined) return { result: fail("old_text needs new_text (an empty string deletes it)."), notes: [rel] };
          const hits = src.split(lf(args.old_text)).length - 1;
          if (hits !== 1)
            return { result: fail(hits ? `old_text occurs ${hits} times in \`${rel}\`; include more context so it matches once.` : `old_text was not found in \`${rel}\`.`), notes: [rel] };
          out = src.replace(lf(args.old_text), () => lf(args.new_text!));
        } else if (args.section !== undefined) {
          if (args.content === undefined) return { result: fail("section needs content."), notes: [rel] };
          out = replaceSection(src, args.section, lf(args.content));
        } else {
          out = src.trimEnd() + "\n\n" + lf(args.append!).trim() + "\n";
        }
        out = out.replace(/^modified: .*$/m, `modified: ${today()}`);
        fs.writeFileSync(abs, out.replace(/\n/g, eol), "utf8");
        index.upsertFile(abs);
        return { result: text(`Edited \`${rel}\`.`), notes: [rel] };
      });
    },
  );

  server.registerTool(
    "brain_move",
    {
      title: "Move or rename a hand-written note",
      description:
        "Move or rename a note within Notes/ and Captures/, for example to promote a capture into Notes/. Refuses to overwrite an existing note, and reports any links that stop resolving.",
      inputSchema: {
        note: z.string().min(1).describe("Note id (vault path), title or [[wikilink]]"),
        to: z.string().min(4).max(240).describe("New vault path, e.g. 'Notes/Harbor Ledger.md'"),
      },
      annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: false },
    },
    async (args, extra) => {
      const p = principalOf(extra as Extra, d);
      return guardedWrite("brain_move", p, args, () => {
        const from = writableNote(args.note, p);
        const to = writable(args.to);
        if (fs.existsSync(to.abs)) return { result: fail(`\`${to.rel}\` already exists.`), notes: [from.rel] };
        const brokenAfter = linksInto(from.note.id);
        fs.mkdirSync(path.dirname(to.abs), { recursive: true });
        fs.renameSync(from.abs, to.abs);
        index.upsertFile(from.abs);
        index.upsertFile(to.abs);
        return { result: text(`Moved \`${from.rel}\` to \`${to.rel}\`.${brokenAfter()}`), notes: [from.rel, to.rel] };
      });
    },
  );

  server.registerTool(
    "brain_delete",
    {
      title: "Delete a hand-written note (to the vault trash)",
      description:
        "Remove a note from Notes/ or Captures/ by moving it into the vault's .trash/ folder, which is never indexed. Nothing is erased; the result gives the path to restore from. Generated notes and the memory file cannot be deleted.",
      inputSchema: {
        note: z.string().min(1).describe("Note id (vault path), title or [[wikilink]]"),
      },
      annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: false },
    },
    async (args, extra) => {
      const p = principalOf(extra as Extra, d);
      return guardedWrite("brain_delete", p, args, () => {
        const { note, abs, rel } = writableNote(args.note, p);
        const brokenAfter = linksInto(note.id);
        const trashRel = `.trash/${new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19)} ${path.posix.basename(rel)}`;
        const trashAbs = path.join(cfg.vaultDir, trashRel);
        fs.mkdirSync(path.dirname(trashAbs), { recursive: true });
        fs.renameSync(abs, trashAbs);
        index.upsertFile(abs);
        return { result: text(`Deleted \`${rel}\`; the file is at \`${trashRel}\` if you need it back.${brokenAfter()}`), notes: [rel] };
      });
    },
  );

  // ------------------------------------------------------------ resources
  server.registerResource(
    "identity",
    "brain://identity",
    { title: "Owner identity bundle", description: "Persona and standing context, same as brain_identity", mimeType: "text/markdown" },
    async (uri, extra) => {
      const p = principalOf(extra as Extra, d);
      const { text: t } = buildIdentity(cfg, index, policy, p);
      return { contents: [{ uri: uri.href, mimeType: "text/markdown", text: policy.redact(t).text }] };
    },
  );

  server.registerResource(
    "note",
    new ResourceTemplate("brain://note/{+path}", { list: undefined }),
    { title: "Vault note", description: "A single note by vault path", mimeType: "text/markdown" },
    async (uri, vars, extra) => {
      const p = principalOf(extra as Extra, d);
      const n = index.resolve(decodeURIComponent(String(vars.path)));
      if (!n || !policy.canRead(n, p)) throw new Error(`Note not found: ${String(vars.path)}`);
      return { contents: [{ uri: uri.href, mimeType: "text/markdown", text: policy.redact(n.body).text }] };
    },
  );

  // ------------------------------------------------------------ prompts
  server.registerPrompt(
    "assume_persona",
    { title: "Assume the owner's assistant persona", description: "Loads the identity bundle into the conversation" },
    async (extra) => {
      const p = principalOf(extra as Extra, d);
      const { text: t } = buildIdentity(cfg, index, policy, p);
      return { messages: [{ role: "user", content: { type: "text", text: `${policy.redact(t).text}\n\nAcknowledge briefly and continue as this assistant.` } }] };
    },
  );

  server.registerPrompt(
    "project_briefing",
    { title: "Brief me on a project", description: "Pulls the project briefing and asks for a summary", argsSchema: { project: z.string().describe("Project name") } },
    async (args, extra) => {
      const p = principalOf(extra as Extra, d);
      const hub = index.hubs().find((h) => h.title.toLowerCase() === args.project.toLowerCase());
      const notes = hub ? readable(index.list({ project: hub.title, limit: 100 }), p) : [];
      const listing = notes.map((n) => `- ${n.title} (${n.type}, ${n.modified})`).join("\n");
      return {
        messages: [
          { role: "user", content: { type: "text", text: `Brief me on ${args.project}. Start from this note list, then call brain_project and brain_read as needed.\n\n${listing || "(no notes found; call brain_project with no arguments to list projects)"}` } },
        ],
      };
    },
  );

  return server;
}

export function fullPrincipal(transport: "stdio" | "http", clientId: string): Principal {
  return { clientId, scopes: new Set(ALL_SCOPES), transport };
}
